// web-next/components/shell/platform-copyright-footer.tsx
import React from 'react';
import { cn } from '../../lib/utils';

type PlatformCopyrightFooterProps = React.HTMLAttributes<HTMLElement> & {
  className?: string;
  innerClassName?: string;
  headlineClassName?: string;
  lineClassName?: string;
  linkClassName?: string;
  version?: string | null;
};

export function PlatformCopyrightFooter({
  className,
  innerClassName,
  headlineClassName,
  lineClassName,
  linkClassName,
  version,
  ...props
}: PlatformCopyrightFooterProps) {
  const currentYear = new Date().getFullYear();

  return (
    <footer className={className} {...props}>
      <div className={innerClassName}>
        <div className={headlineClassName}>
          Apache HertzBeat™{version ? ` ${version}` : ''}
        </div>
        <div className={lineClassName}>
          Copyright &copy; {currentYear}{' '}
          <a href="https://hertzbeat.apache.org" target="_blank" rel="noreferrer" className={cn('underline-offset-2 hover:underline', linkClassName)}>
            Apache HertzBeat™
          </a>
        </div>
        <div className={lineClassName}>Licensed under the Apache License, Version 2.0</div>
      </div>
    </footer>
  );
}

// web-app/src/app/shared/components/platform-copyright-footer/platform-copyright-footer.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { CONSTANTS } from '../../constants';

@Component({
  selector: 'app-platform-copyright-footer',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './platform-copyright-footer.component.html',
  styleUrl: './platform-copyright-footer.component.less'
})
export class PlatformCopyrightFooterComponent {
  @Input() version = CONSTANTS.VERSION;

  readonly currentYear = new Date().getFullYear();
}

<div class="platform-copyright-footer">
  <div class="platform-copyright-footer__headline">
    Apache HertzBeat™<span *ngIf="version"> {{ version }}</span>
  </div>
  <div class="platform-copyright-footer__line">
    Copyright &copy; {{ currentYear }}
    <a href="https://hertzbeat.apache.org" target="_blank" rel="noopener noreferrer">Apache HertzBeat™</a>
  </div>
  <div class="platform-copyright-footer__line">Licensed under the Apache License, Version 2.0</div>
</div>
